// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKKi2p23ai86fgSRTFomlOy3-R624XWpc',
    appId: '1:735534456081:web:de4f028327f70d47ff80b0',
    messagingSenderId: '735534456081',
    projectId: 'fitcore-90e94',
    authDomain: 'fitcore-90e94.firebaseapp.com',
    storageBucket: 'fitcore-90e94.firebasestorage.app',
    measurementId: 'G-JC095Y7CN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJsb5eAVpMs8jNilEB7UFaBwQWxS-dzHE',
    appId: '1:735534456081:android:0fd0e06c850694c8ff80b0',
    messagingSenderId: '735534456081',
    projectId: 'fitcore-90e94',
    storageBucket: 'fitcore-90e94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxHgHF8Q8Am-QEcaKX6Br7nE2RWMxL78M',
    appId: '1:735534456081:ios:00e296d204c63623ff80b0',
    messagingSenderId: '735534456081',
    projectId: 'fitcore-90e94',
    storageBucket: 'fitcore-90e94.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxHgHF8Q8Am-QEcaKX6Br7nE2RWMxL78M',
    appId: '1:735534456081:ios:00e296d204c63623ff80b0',
    messagingSenderId: '735534456081',
    projectId: 'fitcore-90e94',
    storageBucket: 'fitcore-90e94.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKKi2p23ai86fgSRTFomlOy3-R624XWpc',
    appId: '1:735534456081:web:35abe9cce0b2c616ff80b0',
    messagingSenderId: '735534456081',
    projectId: 'fitcore-90e94',
    authDomain: 'fitcore-90e94.firebaseapp.com',
    storageBucket: 'fitcore-90e94.firebasestorage.app',
    measurementId: 'G-9PSSEYE23W',
  );
}
